model_path: /data/users/wjy/models/llava-hf/llava-v1.6-mistral-7b-hf
max_new_tokens: 64
temperature: 0.2
image: data/sample_images/example.jpg
question: "Describe the scene."
hcs:
  use: true
  grids: [[4,4],[8,8]]
  topks: [6,8]
